import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { VeniaProvider } from "@venia/react";
import '@venia/theme-default/banner.css';
import "./globals.css";
import { veniaConfig } from "@/config/venia";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <Script
        src="/test.js"
        type="text/plain"
        data-venia-category="marketing"
      />
      <body className="min-h-full flex flex-col">
        <VeniaProvider
          config={veniaConfig}
          mode="modal"
        >
          {children}
        </VeniaProvider>
      </body>
    </html>
  );
}
