import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { VeniaProvider } from '@venia/react'
import '@venia/theme-default/banner.css'
import './globals.css'
import { veniaConfig } from '@/config/venia'
import Script from 'next/script'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <Script
        data-venia-category="functional"
        type="text/plain"
        dangerouslySetInnerHTML={{
          __html: "console.log('Log from inline script');",
        }}
      />
      <Script data-venia-category="analytics" type="text/plain" src="/analytics.js" />
      <body className="min-h-full flex flex-col">
        <VeniaProvider config={veniaConfig} mode="banner">
          {children}
        </VeniaProvider>
      </body>
    </html>
  )
}
